on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          cache-on-failure: "true"

      - shell: bash
        run: just install

      - shell: bash
        run: cargo sqlx prepare --check

      - shell: bash
        run: cargo fmt --check

      - shell: bash
        run: cargo check

      - shell: bash
        run: cargo check --tests

      - shell: bash
        run: cargo clippy -- -D warnings

      - shell: bash
        run: cargo test --all
